/**
 * 220 BioWorX — Research catalog
 * Research grade materials. Not FDA approved.
 * Not for human or veterinary use.
 */
window.BW_PRODUCTS = [
  {
    id: "glp3-rt-30",
    sku: "RETA-30",
    name: "Reta (GLP-3 RT)",
    strength: "30 mg",
    form: "Lyophilized research peptide",
    category: "Incretin-pathway research",
    unitPrice: 140,
    unit: "vial",
    image: "images/products/reta-klow.jpeg",
    images: ["images/products/reta-klow.jpeg"],
    shortDescription:
      "Research-grade Reta / GLP-3 RT, 30 mg, for laboratory investigation of multi-agonist incretin pathway models.",
    description:
      "Reta (GLP-3 RT) 30 mg is a research-grade lyophilized peptide for qualified laboratory use only. Not FDA approved. Not a drug or compounded medication. Not for human or veterinary use, diagnosis, treatment, cure, or prevention of any disease.",
    scientificName: "Reta / GLP-3 RT (research designation)",
    molecularWeight: "Multi-agonist research peptide (batch-dependent)",
    formula: "See product labeling / research documentation",
    sequence: "Available to qualified research accounts on request",
    appearance: "White to off-white lyophilized solid (typical)",
    storage: "Store frozen, protected from light and moisture. Laboratory handling only.",
    researchNotes: "Research grade only. Not FDA approved for any indication or use.",
    tags: ["reta", "GLP-3", "30mg"],
  },
  {
    id: "tirz-40",
    sku: "TIRZ-40",
    name: "Tirz (GLP)",
    strength: "40 mg",
    form: "Lyophilized research peptide",
    category: "Incretin-pathway research",
    unitPrice: 150,
    unit: "vial",
    image: "images/products/tirz-light.jpeg",
    images: [
      "images/products/tirz-light.jpeg",
      "images/products/tirz-dark.jpeg",
    ],
    shortDescription:
      "Research-grade Tirz-class dual incretin pathway peptide, 40 mg per vial.",
    description:
      "Tirz 40 mg is research-grade material for non-clinical laboratory study of dual incretin-related pathways. Not FDA approved. Not for human consumption, clinical administration, or compounding into patient medications.",
    scientificName: "Tirz-class dual incretin pathway research peptide",
    molecularWeight: "~4810–4814 g·mol⁻¹ (typical literature range)",
    formula: "See research sequence documentation",
    sequence: "Available to qualified research purchasers on request",
    appearance: "Lyophilized solid",
    storage: "Frozen, dry, protected from light. Laboratory controls only.",
    researchNotes: "Research grade only. Not FDA approved for any use.",
    tags: ["tirz", "incretin", "40mg"],
  },
  {
    id: "bpc-157-10",
    sku: "BPC-157-10",
    name: "BPC-157",
    strength: "10 mg",
    form: "Lyophilized research peptide",
    category: "Synthetic peptide research",
    unitPrice: 40,
    unit: "vial",
    image: "images/products/bpc-157-light.jpeg",
    images: [
      "images/products/bpc-157-light.jpeg",
      "images/products/bpc-157-dark.jpeg",
    ],
    shortDescription:
      "Research-grade synthetic pentadecapeptide (BPC-157), 10 mg.",
    description:
      "BPC-157 is a research-grade synthetic peptide for lawful laboratory research only. Not FDA approved. Not intended for human or animal clinical use. No therapeutic claims are made.",
    scientificName: "BPC-157 (GEPPPGKPADDAGLV; research pentadecapeptide)",
    molecularWeight: "1419.5 g·mol⁻¹ (typical)",
    formula: "C₆₂H₉₈N₁₆O₂₂ (typical)",
    sequence: "Gly-Glu-Pro-Pro-Pro-Gly-Lys-Pro-Ala-Asp-Asp-Ala-Gly-Leu-Val (GEPPPGKPADDAGLV)",
    appearance: "White to off-white lyophilized powder (typical)",
    storage: "−20 °C recommended for lyophilizate; protect from moisture and light.",
    researchNotes: "Research grade only. Not FDA approved.",
    tags: ["BPC-157", "10mg"],
  },
  {
    id: "tb-500-10",
    sku: "TB-500-10",
    name: "TB-500",
    strength: "10 mg",
    form: "Lyophilized research peptide",
    category: "Synthetic peptide research",
    unitPrice: 60,
    unit: "vial",
    image: "images/products/tb500-light.jpeg",
    images: [
      "images/products/tb500-light.jpeg",
      "images/products/tb500-dark.jpeg",
    ],
    shortDescription:
      "Research-grade TB-500 peptide, 10 mg, for non-clinical laboratory research.",
    description:
      "TB-500 is research-grade material for laboratory use only. Not FDA approved. Not for human or veterinary use.",
    scientificName: "TB-500 (thymosin β4–related research peptide)",
    molecularWeight: "Batch-defined research material",
    formula: "See research documentation",
    sequence: "See research documentation for this SKU",
    appearance: "Lyophilized solid",
    storage: "Store frozen, dry, protected from light.",
    researchNotes: "Research grade only. Not FDA approved.",
    tags: ["TB-500", "10mg"],
  },
  {
    id: "klow-80",
    sku: "KLOW-80",
    name: "KLOW Blend",
    strength: "80 mg total",
    form: "Lyophilized multi-peptide research blend",
    category: "Research blends",
    unitPrice: 80,
    unit: "vial",
    image: "images/products/klow-light.jpeg",
    images: [
      "images/products/klow-light.jpeg",
      "images/products/klow-dark.jpeg",
    ],
    shortDescription:
      "Research-grade 80 mg blend: 50 mg GHK-Cu, 10 mg TB-500, 10 mg BPC-157, 10 mg KPV.",
    description:
      "KLOW is a research-grade multi-component lyophilized blend (80 mg total). Label composition: GHK-Cu 50 mg, TB-500 10 mg, BPC-157 10 mg, KPV 10 mg. Not FDA approved. Not for human or veterinary use. Not a 503A/503B compounded drug.",
    scientificName: "KLOW multi-peptide research blend",
    molecularWeight: "Component-specific (see blend breakdown)",
    formula: "Multi-component blend",
    sequence: "See individual components",
    appearance: "Lyophilized solid (color may reflect copper-peptide component)",
    storage: "Frozen, dry, protected from light.",
    blendComponents: [
      { name: "GHK-Cu", amount: "50 mg", mw: "~403.9 g·mol⁻¹ (complex; peptide ~340.4)" },
      { name: "TB-500", amount: "10 mg", mw: "Batch-defined" },
      { name: "BPC-157", amount: "10 mg", mw: "1419.5 g·mol⁻¹ (typical)" },
      { name: "KPV", amount: "10 mg", mw: "342.4 g·mol⁻¹ (typical)" },
    ],
    researchNotes: "Research grade blend only. Not FDA approved.",
    tags: ["blend", "KLOW", "80mg"],
  },
  {
    id: "kpv-10",
    sku: "KPV-10",
    name: "KPV",
    strength: "10 mg",
    form: "Lyophilized research peptide",
    category: "Synthetic peptide research",
    unitPrice: 50,
    unit: "vial",
    image: "images/products/kpv-10.svg",
    images: ["images/products/kpv-10.svg"],
    shortDescription: "Research-grade KPV tripeptide, 10 mg.",
    description:
      "KPV (Lys-Pro-Val) is a research-grade synthetic tripeptide for laboratory use only. Not FDA approved. Not for human or veterinary administration or consumption.",
    scientificName: "KPV (L-lysyl-L-prolyl-L-valine)",
    molecularWeight: "342.4 g·mol⁻¹ (typical)",
    formula: "C₁₆H₃₀N₄O₄ (typical)",
    sequence: "Lys-Pro-Val (KPV)",
    appearance: "Lyophilized solid",
    storage: "Frozen, dry, protected from light.",
    researchNotes: "Research grade only. Not FDA approved. Dedicated vial photos can replace the placeholder when available.",
    tags: ["KPV", "10mg"],
  },
  {
    id: "ghk-cu-100",
    sku: "GHK-CU-100",
    name: "GHK-Cu",
    strength: "100 mg",
    form: "Lyophilized research copper peptide",
    category: "Copper peptide research",
    unitPrice: 50,
    unit: "vial",
    image: "images/products/klow-light.jpeg",
    images: [
      "images/products/klow-light.jpeg",
      "images/products/klow-dark.jpeg",
    ],
    shortDescription:
      "Research-grade GHK-Cu copper tripeptide, 100 mg.",
    description:
      "Glycyl-L-histidyl-L-lysine copper complex (GHK-Cu) is research-grade material for laboratory use only. Not FDA approved. Not for human or veterinary use.",
    scientificName: "GHK-Cu (glycyl-L-histidyl-L-lysine copper complex)",
    molecularWeight: "Peptide ~340.4 g·mol⁻¹; Cu complex ~403.9 g·mol⁻¹ (typical)",
    formula: "C₁₄H₂₄N₆O₄ · Cu (typical complex representation)",
    sequence: "Gly-His-Lys (GHK) complexed with copper(II)",
    appearance: "Blue to blue-green lyophilized solid (typical for Cu peptide)",
    storage: "Frozen, dry, protected from light.",
    researchNotes:
      "Research grade only. Not FDA approved. Gallery uses related brand photography until dedicated GHK-Cu pack shots are uploaded.",
    tags: ["GHK-Cu", "100mg"],
  },
  {
    id: "cjc-ipa-20",
    sku: "CJC-IPA-20",
    name: "CJC-1295 (No DAC) + Ipamorelin",
    strength: "10 mg + 10 mg (20 mg total)",
    form: "Lyophilized dual-peptide research vial",
    category: "GHRH / GHS pathway research",
    unitPrice: 100,
    unit: "vial",
    image: "images/products/cjc-ipa-light.jpeg",
    images: [
      "images/products/cjc-ipa-light.jpeg",
      "images/products/cjc-ipa-dark.jpeg",
    ],
    shortDescription:
      "Research-grade dual vial: CJC-1295 (No DAC) 10 mg + Ipamorelin 10 mg.",
    description:
      "Research-grade dual-fill vial for laboratory study of GHRH-analogue and ghrelin-mimetic pathway models. Not FDA approved. Not for human or veterinary use.",
    scientificName: "CJC-1295 (modGRF 1-29, no DAC) + Ipamorelin",
    molecularWeight:
      "CJC-1295 no DAC ~3367.9 g·mol⁻¹ (typical); Ipamorelin ~711.9 g·mol⁻¹ (typical)",
    formula: "See component research documentation",
    sequence:
      "CJC-1295 (No DAC): modified GRF(1-29) analogue without Drug Affinity Complex. Ipamorelin: Aib-His-D-2-Nal-D-Phe-Lys-NH₂ (typical).",
    appearance: "Lyophilized solid",
    storage: "Frozen, dry, protected from light.",
    blendComponents: [
      { name: "CJC-1295 (No DAC)", amount: "10 mg", mw: "~3367.9 g·mol⁻¹ (typical)" },
      { name: "Ipamorelin", amount: "10 mg", mw: "~711.9 g·mol⁻¹ (typical)" },
    ],
    researchNotes: "Research grade only. Not FDA approved.",
    tags: ["CJC-1295", "Ipamorelin", "20mg"],
  },
  {
    id: "mots-c-40",
    sku: "MOTSC-40",
    name: "MOTS-c",
    strength: "40 mg",
    form: "Lyophilized research peptide",
    category: "Mitochondrial peptide research",
    unitPrice: 75,
    unit: "vial",
    image: "images/products/motsc-light.jpeg",
    images: [
      "images/products/motsc-light.jpeg",
      "images/products/motsc-dark.jpeg",
    ],
    shortDescription:
      "Research-grade MOTS-c mitochondrial peptide, 40 mg.",
    description:
      "MOTS-c is a research-grade mitochondrial open reading frame–encoded peptide for non-clinical laboratory research. Not FDA approved. Not for human or veterinary use.",
    scientificName: "MOTS-c (mitochondrial ORF-derived peptide)",
    molecularWeight: "~2174.6 g·mol⁻¹ (typical)",
    formula: "See research documentation",
    sequence: "MRWQEMGYIFYPRKLR (typical human MOTS-c sequence)",
    appearance: "Lyophilized solid",
    storage: "Frozen, dry, protected from light.",
    researchNotes: "Research grade only. Not FDA approved.",
    tags: ["MOTS-c", "40mg"],
  },
  {
    id: "nad-1000",
    sku: "NAD-1000",
    name: "NAD+",
    strength: "1000 mg",
    form: "Research chemical (β-nicotinamide adenine dinucleotide)",
    category: "Cofactor / nucleotide research",
    unitPrice: 80,
    unit: "vial",
    image: "images/products/nad-light.jpeg",
    images: [
      "images/products/nad-light.jpeg",
      "images/products/nad-dark.jpeg",
    ],
    shortDescription: "Research-grade NAD+, 1000 mg, laboratory biochemical only.",
    description:
      "Nicotinamide adenine dinucleotide (NAD+, oxidized form) is research-grade laboratory material. Not FDA approved as a drug or supplement. Not for human injection, infusion, or dietary use.",
    scientificName: "β-Nicotinamide adenine dinucleotide (oxidized), NAD+",
    molecularWeight: "663.43 g·mol⁻¹",
    formula: "C₂₁H₂₆N₇O₁₄P₂",
    sequence: "N/A (dinucleotide cofactor)",
    appearance: "White to yellowish solid or lyophilized material (lot-dependent)",
    storage: "Store cold, dry, protected from light and moisture.",
    researchNotes: "Research grade only. Not FDA approved. Handle under institutional chemical hygiene plans.",
    tags: ["NAD+", "1000mg"],
  },
  {
    id: "wolverine",
    sku: "WOLVERINE",
    name: "Wolverine Bundle",
    strength: "Bundle",
    form: "Multi-vial research bundle",
    category: "Bundles",
    unitPrice: 100,
    unit: "bundle",
    image: "images/products/wolverine-light.jpeg",
    images: [
      "images/products/wolverine-light.jpeg",
      "images/products/bpc-157-light.jpeg",
      "images/products/tb500-light.jpeg",
    ],
    shortDescription:
      "Research bundle: BPC-157 10 mg + TB-500 10 mg.",
    description:
      "Wolverine is a research-grade bundle pairing BPC-157 (10 mg) and TB-500 (10 mg) for laboratory programs. Not FDA approved. Not for human or veterinary use. Not a compounded drug product.",
    scientificName: "BPC-157 + TB-500 research bundle",
    molecularWeight: "See BPC-157 and TB-500 component specs",
    formula: "Multi-vial bundle",
    sequence: "See components",
    appearance: "Research vials as packed",
    storage: "Frozen, dry, protected from light.",
    blendComponents: [
      { name: "BPC-157", amount: "10 mg", mw: "1419.5 g·mol⁻¹ (typical)" },
      { name: "TB-500", amount: "10 mg", mw: "Batch-defined" },
    ],
    researchNotes: "Research grade bundle only. Not FDA approved.",
    tags: ["bundle", "Wolverine", "BPC-157", "TB-500"],
  },
  {
    id: "nad-ghk",
    sku: "NAD-GHK",
    name: "NAD+ + GHK-Cu Bundle",
    strength: "1000 mg + 100 mg",
    form: "Multi-vial research bundle",
    category: "Bundles",
    unitPrice: 130,
    unit: "bundle",
    image: "images/products/nad-light.jpeg",
    images: [
      "images/products/nad-light.jpeg",
      "images/products/nad-dark.jpeg",
      "images/products/klow-light.jpeg",
      "images/products/klow-dark.jpeg",
    ],
    shortDescription:
      "Research bundle: NAD+ 1000 mg + GHK-Cu 100 mg.",
    description:
      "Paired research-grade materials: NAD+ (1000 mg) and GHK-Cu (100 mg) for laboratory use only. Not FDA approved. Not for human or veterinary use.",
    scientificName: "NAD+ + GHK-Cu research bundle",
    molecularWeight: "NAD+ 663.43 g·mol⁻¹; GHK-Cu complex ~403.9 g·mol⁻¹ (typical)",
    formula: "Multi-vial bundle",
    sequence: "See components",
    appearance: "Research vials as packed",
    storage: "Cold/dry per component storage guidance.",
    blendComponents: [
      { name: "NAD+", amount: "1000 mg", mw: "663.43 g·mol⁻¹" },
      { name: "GHK-Cu", amount: "100 mg", mw: "~403.9 g·mol⁻¹ (complex, typical)" },
    ],
    researchNotes: "Research grade bundle only. Not FDA approved.",
    tags: ["bundle", "NAD+", "GHK-Cu"],
  },
  {
    id: "reta-klow",
    sku: "RETA-KLOW",
    name: "Reta + KLOW Bundle",
    strength: "30 mg + 80 mg",
    form: "Multi-vial research bundle",
    category: "Bundles",
    unitPrice: 200,
    unit: "bundle",
    image: "images/products/reta-klow.jpeg",
    images: [
      "images/products/reta-klow.jpeg",
      "images/products/klow-light.jpeg",
      "images/products/klow-dark.jpeg",
    ],
    shortDescription:
      "Research bundle: Reta (GLP-3 RT) 30 mg + KLOW blend 80 mg.",
    description:
      "Research-grade bundle pairing Reta / GLP-3 RT (30 mg) with KLOW (80 mg total: GHK-Cu 50 mg, TB-500 10 mg, BPC-157 10 mg, KPV 10 mg). Not FDA approved. Not for human or veterinary use.",
    scientificName: "Reta (GLP-3 RT) + KLOW research bundle",
    molecularWeight: "See component specs",
    formula: "Multi-vial bundle",
    sequence: "See components",
    appearance: "Research vials as packed",
    storage: "Frozen, dry, protected from light.",
    blendComponents: [
      { name: "Reta (GLP-3 RT)", amount: "30 mg", mw: "Batch-dependent" },
      { name: "KLOW blend", amount: "80 mg total", mw: "See KLOW components" },
    ],
    researchNotes: "Research grade bundle only. Not FDA approved.",
    tags: ["bundle", "Reta", "KLOW"],
  },
];

window.BW_getProduct = function (idOrSku) {
  const q = String(idOrSku || "").toLowerCase();
  return (
    window.BW_PRODUCTS.find(
      (p) => p.id.toLowerCase() === q || p.sku.toLowerCase() === q
    ) || null
  );
};

/** Fallback image if a product photo fails to load */
window.BW_IMG_FALLBACK = "images/products/klow-light.jpeg";
