/**
 * 220 BioWorX — Research catalog
 * Research grade materials. Not FDA approved.
 * Not for human or veterinary use.
 */
window.BW_PRODUCTS = [
  {
    id: "glp3-rt-30",
    sku: "RETA-30",
    name: "Reta (GLP-3 RT)",
    strength: "30 mg",
    form: "Lyophilized research peptide",
    category: "Incretin-pathway research",
    unitPrice: 120,
    unit: "vial",
    image: "images/products/glp3-rt-light.jpeg",
    images: [
      "images/products/glp3-rt-light.jpeg",
      "images/products/glp3-rt-dark.jpeg",
      {
        src: "images/products/coas/glp3-rt-30-coa-p1.png",
        kind: "coa",
        label: "COA",
        alt: "Certificate of Analysis — Reta (GLP-3 RT) 30 mg (view only)",
      },
      {
        src: "images/products/coas/glp3-rt-30-janoshik-p1.png",
        kind: "coa",
        label: "COA 2",
        alt: "Test report — Reta (GLP-3 RT) 30 mg (view only)",
      },
    ],
    shortDescription:
      "Research-grade Reta / GLP-3 RT, 30 mg, for laboratory investigation of multi-agonist incretin pathway models.",
    description:
      "Reta (GLP-3 RT) 30 mg is a research-grade lyophilized peptide for qualified laboratory use only. Not FDA approved. Not a drug or compounded medication. Not for human or veterinary use, diagnosis, treatment, cure, or prevention of any disease.",
    scientificName: "Reta / GLP-3 RT (research designation)",
    molecularWeight: "Multi-agonist research peptide (batch-dependent)",
    formula: "See product labeling / research documentation",
    sequence: "Available to qualified research accounts on request",
    appearance: "White to off-white lyophilized solid (typical)",
    storage: "Store frozen, protected from light and moisture. Laboratory handling only.",
    researchNotes: "Research grade only. Not FDA approved for any indication or use.",
    tags: ["reta", "GLP-3", "30mg"],
  },
  {
    id: "glp3-rt-20",
    sku: "RETA-20",
    name: "Reta (GLP-3 RT)",
    strength: "20 mg",
    form: "Lyophilized research peptide",
    category: "Incretin-pathway research",
    unitPrice: 100,
    unit: "vial",
    image: "images/products/glp3-rt-light.jpeg",
    images: [
      "images/products/glp3-rt-light.jpeg",
      "images/products/glp3-rt-dark.jpeg",
      {
        src: "images/products/coas/reta-20-janoshik-p1.png",
        kind: "coa",
        label: "COA",
        alt: "Test report — Reta (GLP-3 RT) 20 mg (view only)",
      },
    ],
    shortDescription:
      "Research-grade Reta / GLP-3 RT, 20 mg, for laboratory investigation of multi-agonist incretin pathway models.",
    description:
      "Reta (GLP-3 RT) 20 mg is a research-grade lyophilized peptide for qualified laboratory use only. Not FDA approved. Not a drug or compounded medication. Not for human or veterinary use, diagnosis, treatment, cure, or prevention of any disease.",
    scientificName: "Reta / GLP-3 RT (research designation)",
    molecularWeight: "Multi-agonist research peptide (batch-dependent)",
    formula: "See product labeling / research documentation",
    sequence: "Available to qualified research accounts on request",
    appearance: "White to off-white lyophilized solid (typical)",
    storage: "Store frozen, protected from light and moisture. Laboratory handling only.",
    researchNotes: "Research grade only. Not FDA approved for any indication or use.",
    tags: ["reta", "GLP-3", "20mg"],
  },
  {
    id: "tirz-40",
    sku: "GLP2-TR-40",
    name: "GLP-2 TR",
    strength: "40 mg",
    form: "Lyophilized research peptide",
    category: "Incretin-pathway research",
    unitPrice: 100,
    unit: "vial",
    image: "images/products/tirz-light.jpeg",
    images: [
      "images/products/tirz-light.jpeg",
      "images/products/tirz-dark.jpeg",
      {
        src: "images/products/coas/glp2-tr-40-coa-p1.png",
        kind: "coa",
        label: "COA",
        alt: "Certificate of Analysis — GLP-2 TR 40 mg (view only)",
      },
    ],
    shortDescription:
      "Research-grade dual GIP / GLP-1 receptor agonist peptide, 40 mg per vial, for laboratory research only.",
    description:
      "GLP-2 TR 40 mg is research-grade lyophilized material for non-clinical laboratory investigation of dual glucose-dependent insulinotropic polypeptide (GIP) and glucagon-like peptide-1 (GLP-1) receptor pathway models. Not FDA approved. Not for human consumption, clinical administration, or compounding into patient medications.",
    scientificName: "Dual GIP / GLP-1 receptor agonist research peptide (39-amino-acid synthetic peptide)",
    molecularWeight: "4813.45 g·mol⁻¹",
    formula: "C₂₂₅H₃₄₈N₄₈O₆₈",
    sequence:
      "Tyr-Aib-Glu-Gly-Thr-Phe-Thr-Ser-Asp-Tyr-Ser-Ile-Aib-Leu-Asp-Lys-Ile-Ala-Gln-Lys-Ala-Phe-Val-Gln-Trp-Leu-Ile-Ala-Gly-Gly-Pro-Ser-Ser-Gly-Ala-Pro-Pro-Pro-Ser-NH₂ (C20 fatty-diacid acylation on Lys side chain as described for this dual-agonist research structure)",
    appearance: "White to off-white lyophilized solid (typical)",
    storage: "Frozen, dry, protected from light. Laboratory controls only.",
    researchNotes:
      "Catalog name GLP-2 TR denotes this research SKU only. Research grade. Not FDA approved for any use. Not for human or veterinary use.",
    tags: ["GLP-2 TR", "incretin", "40mg"],
  },
  {
    id: "bpc-157-10",
    sku: "BPC-157-10",
    name: "BPC-157",
    strength: "10 mg",
    form: "Lyophilized research peptide",
    category: "Synthetic peptide research",
    unitPrice: 40,
    unit: "vial",
    image: "images/products/bpc-157-light.jpeg",
    images: [
      "images/products/bpc-157-light.jpeg",
      "images/products/bpc-157-dark.jpeg",
      {
        src: "images/products/coas/bpc-157-10-coa-p1.png",
        kind: "coa",
        label: "COA",
        alt: "Certificate of Analysis — BPC-157 10 mg (view only)",
      },
    ],
    shortDescription:
      "Research-grade synthetic pentadecapeptide (BPC-157), 10 mg.",
    description:
      "BPC-157 is a research-grade synthetic peptide for lawful laboratory research only. Not FDA approved. Not intended for human or animal clinical use. No therapeutic claims are made.",
    scientificName: "BPC-157 (GEPPPGKPADDAGLV; research pentadecapeptide)",
    molecularWeight: "1419.5 g·mol⁻¹ (typical)",
    formula: "C₆₂H₉₈N₁₆O₂₂ (typical)",
    sequence: "Gly-Glu-Pro-Pro-Pro-Gly-Lys-Pro-Ala-Asp-Asp-Ala-Gly-Leu-Val (GEPPPGKPADDAGLV)",
    appearance: "White to off-white lyophilized powder (typical)",
    storage: "−20 °C recommended for lyophilizate; protect from moisture and light.",
    researchNotes: "Research grade only. Not FDA approved.",
    tags: ["BPC-157", "10mg"],
  },
  {
    id: "tesamorelin-10",
    sku: "TESA-10",
    name: "Tesamorelin",
    strength: "10 mg",
    form: "Lyophilized research peptide",
    category: "GHRH-analogue research",
    unitPrice: 70,
    unit: "vial",
    image: "images/products/tesamorelin-10-light.jpeg",
    images: [
      "images/products/tesamorelin-10-light.jpeg",
      "images/products/tesamorelin-10-dark.jpeg",
      "images/products/tesamorelin-10-label.jpg",
      {
        src: "images/products/coas/tesamorelin-10-coa-p1.png",
        kind: "coa",
        label: "COA",
        alt: "Certificate of Analysis — Tesamorelin 10 mg (view only)",
      },
    ],
    shortDescription:
      "Research-grade Tesamorelin, 10 mg lyophilized, for laboratory research only.",
    description:
      "Tesamorelin 10 mg is a research-grade lyophilized peptide for qualified laboratory use only. Not FDA approved. Not a drug or compounded medication. Not for human or veterinary use, diagnosis, treatment, cure, or prevention of any disease.",
    scientificName: "Tesamorelin (GHRH analogue research peptide)",
    molecularWeight: "Batch-defined research material",
    formula: "See research documentation / product labeling",
    sequence: "Available to qualified research accounts on request",
    appearance: "White to off-white lyophilized solid (typical)",
    storage: "Store frozen, protected from light and moisture. Laboratory handling only.",
    researchNotes: "Research grade only. Not FDA approved for any indication or use. Batch ERP71726 per COA.",
    tags: ["Tesamorelin", "Tesa", "10mg", "GHRH"],
  },
  {
    id: "tb-500-10",
    sku: "TB-500-10",
    name: "TB-500",
    strength: "10 mg",
    form: "Lyophilized research peptide",
    category: "Synthetic peptide research",
    unitPrice: 60,
    unit: "vial",
    image: "images/products/tb500-light.jpeg",
    images: [
      "images/products/tb500-light.jpeg",
      "images/products/tb500-dark.jpeg",
    ],
    shortDescription:
      "Research-grade TB-500 peptide, 10 mg, for non-clinical laboratory research.",
    description:
      "TB-500 is research-grade material for laboratory use only. Not FDA approved. Not for human or veterinary use.",
    scientificName: "TB-500 (thymosin β4–related research peptide)",
    molecularWeight: "Batch-defined research material",
    formula: "See research documentation",
    sequence: "See research documentation for this SKU",
    appearance: "Lyophilized solid",
    storage: "Store frozen, dry, protected from light.",
    researchNotes: "Research grade only. Not FDA approved.",
    tags: ["TB-500", "10mg"],
  },
  {
    id: "klow-80",
    sku: "KLOW-80",
    name: "KLOW Blend",
    strength: "80 mg total",
    form: "Lyophilized multi-peptide research blend",
    category: "Research blends",
    unitPrice: 80,
    unit: "vial",
    image: "images/products/klow-light.jpeg",
    images: [
      "images/products/klow-light.jpeg",
      "images/products/klow-dark.jpeg",
      {
        src: "images/products/coas/klow-80-coa-p1.png",
        kind: "coa",
        label: "COA",
        alt: "Certificate of Analysis — KLOW Blend 80 mg (view only)",
      },
    ],
    shortDescription:
      "Research-grade 80 mg blend: 50 mg GHK-Cu, 10 mg TB-500, 10 mg BPC-157, 10 mg KPV.",
    description:
      "KLOW is a research-grade multi-component lyophilized blend (80 mg total). Label composition: GHK-Cu 50 mg, TB-500 10 mg, BPC-157 10 mg, KPV 10 mg. Not FDA approved. Not for human or veterinary use. Not a 503A/503B compounded drug.",
    scientificName: "KLOW multi-peptide research blend",
    molecularWeight: "Component-specific (see blend breakdown)",
    formula: "Multi-component blend",
    sequence: "See individual components",
    appearance: "Lyophilized solid (color may reflect copper-peptide component)",
    storage: "Frozen, dry, protected from light.",
    blendComponents: [
      { name: "GHK-Cu", amount: "50 mg", mw: "~403.9 g·mol⁻¹ (complex; peptide ~340.4)" },
      { name: "TB-500", amount: "10 mg", mw: "Batch-defined" },
      { name: "BPC-157", amount: "10 mg", mw: "1419.5 g·mol⁻¹ (typical)" },
      { name: "KPV", amount: "10 mg", mw: "342.4 g·mol⁻¹ (typical)" },
    ],
    researchNotes: "Research grade blend only. Not FDA approved.",
    tags: ["blend", "KLOW", "80mg"],
  },
  {
    id: "kpv-10",
    sku: "KPV-10",
    name: "KPV",
    strength: "10 mg",
    form: "Lyophilized research peptide",
    category: "Synthetic peptide research",
    unitPrice: 50,
    unit: "vial",
    image: "images/products/kpv-10.svg",
    images: ["images/products/kpv-10.svg"],
    shortDescription: "Research-grade KPV tripeptide, 10 mg.",
    description:
      "KPV (Lys-Pro-Val) is a research-grade synthetic tripeptide for laboratory use only. Not FDA approved. Not for human or veterinary administration or consumption.",
    scientificName: "KPV (L-lysyl-L-prolyl-L-valine)",
    molecularWeight: "342.4 g·mol⁻¹ (typical)",
    formula: "C₁₆H₃₀N₄O₄ (typical)",
    sequence: "Lys-Pro-Val (KPV)",
    appearance: "Lyophilized solid",
    storage: "Frozen, dry, protected from light.",
    researchNotes: "Research grade only. Not FDA approved.",
    tags: ["KPV", "10mg"],
  },
  {
    id: "ghk-cu-100",
    sku: "GHK-CU-100",
    name: "GHK-Cu",
    strength: "100 mg",
    form: "Lyophilized research copper peptide",
    category: "Copper peptide research",
    unitPrice: 40,
    unit: "vial",
    image: "images/products/ghk-cu-light.jpeg",
    images: [
      "images/products/ghk-cu-light.jpeg",
      "images/products/ghk-cu-dark.jpeg",
    ],
    shortDescription:
      "Research-grade GHK-Cu copper tripeptide, 100 mg.",
    description:
      "Glycyl-L-histidyl-L-lysine copper complex (GHK-Cu) is research-grade material for laboratory use only. Not FDA approved. Not for human or veterinary use.",
    scientificName: "GHK-Cu (glycyl-L-histidyl-L-lysine copper complex)",
    molecularWeight: "Peptide ~340.4 g·mol⁻¹; Cu complex ~403.9 g·mol⁻¹ (typical)",
    formula: "C₁₄H₂₄N₆O₄ · Cu (typical complex representation)",
    sequence: "Gly-His-Lys (GHK) complexed with copper(II)",
    appearance: "Blue to blue-green lyophilized solid (typical for Cu peptide)",
    storage: "Frozen, dry, protected from light.",
    researchNotes: "Research grade only. Not FDA approved.",
    tags: ["GHK-Cu", "100mg"],
  },
  {
    id: "ss-31-10",
    sku: "SS-31-10",
    name: "SS-31",
    strength: "10 mg",
    form: "Lyophilized research peptide",
    category: "Mitochondrial peptide research",
    unitPrice: 40,
    unit: "vial",
    image: "images/products/ss-31-10.svg",
    images: ["images/products/ss-31-10.svg"],
    shortDescription:
      "Research-grade SS-31 (elamipretide-class) peptide, 10 mg, laboratory use only.",
    description:
      "SS-31 is a research-grade synthetic peptide for non-clinical laboratory investigation of mitochondrial membrane models. Not FDA approved. Not for human or veterinary use, diagnosis, treatment, cure, or prevention of any disease.",
    scientificName: "SS-31 (mitochondria-targeted research peptide)",
    molecularWeight: "Batch-defined research material",
    formula: "See research documentation",
    sequence: "Available to qualified research accounts on request",
    appearance: "Lyophilized solid (typical)",
    storage: "Frozen, dry, protected from light.",
    researchNotes: "Research grade only. Not FDA approved.",
    tags: ["SS-31", "10mg"],
  },
  {
    id: "cjc-ipa-20",
    sku: "CJC-IPA-20",
    name: "CJC-1295 (No DAC) + Ipamorelin",
    strength: "10 mg + 10 mg (20 mg total)",
    form: "Lyophilized dual-peptide research vial",
    category: "GHRH / GHS pathway research",
    unitPrice: 100,
    unit: "vial",
    image: "images/products/cjc-ipa-light.jpeg",
    images: [
      "images/products/cjc-ipa-light.jpeg",
      "images/products/cjc-ipa-dark.jpeg",
    ],
    shortDescription:
      "Research-grade dual vial: CJC-1295 (No DAC) 10 mg + Ipamorelin 10 mg.",
    description:
      "Research-grade dual-fill vial for laboratory study of GHRH-analogue and ghrelin-mimetic pathway models. Not FDA approved. Not for human or veterinary use.",
    scientificName: "CJC-1295 (modGRF 1-29, no DAC) + Ipamorelin",
    molecularWeight:
      "CJC-1295 no DAC ~3367.9 g·mol⁻¹ (typical); Ipamorelin ~711.9 g·mol⁻¹ (typical)",
    formula: "See component research documentation",
    sequence:
      "CJC-1295 (No DAC): modified GRF(1-29) analogue without Drug Affinity Complex. Ipamorelin: Aib-His-D-2-Nal-D-Phe-Lys-NH₂ (typical).",
    appearance: "Lyophilized solid",
    storage: "Frozen, dry, protected from light.",
    blendComponents: [
      { name: "CJC-1295 (No DAC)", amount: "10 mg", mw: "~3367.9 g·mol⁻¹ (typical)" },
      { name: "Ipamorelin", amount: "10 mg", mw: "~711.9 g·mol⁻¹ (typical)" },
    ],
    researchNotes: "Research grade only. Not FDA approved.",
    tags: ["CJC-1295", "Ipamorelin", "20mg"],
  },
  {
    id: "mots-c-40",
    sku: "MOTSC-40",
    name: "MOTS-c",
    strength: "40 mg",
    form: "Lyophilized research peptide",
    category: "Mitochondrial peptide research",
    unitPrice: 75,
    unit: "vial",
    image: "images/products/motsc-light.jpeg",
    images: [
      "images/products/motsc-light.jpeg",
      "images/products/motsc-dark.jpeg",
      {
        src: "images/products/coas/motsc-40-coa-p1.png",
        kind: "coa",
        label: "COA",
        alt: "Certificate of Analysis — MOTS-c 40 mg lot 42526 (view only)",
      },
      {
        src: "images/products/coas/motsc-40-endo-p1.png",
        kind: "coa",
        label: "Endo",
        alt: "Endotoxin analysis — MOTS-c 40 mg lot 42526 (view only)",
      },
    ],
    shortDescription:
      "Research-grade MOTS-c mitochondrial peptide, 40 mg.",
    description:
      "MOTS-c is a research-grade mitochondrial open reading frame–encoded peptide for non-clinical laboratory research. Not FDA approved. Not for human or veterinary use.",
    scientificName: "MOTS-c (mitochondrial ORF-derived peptide)",
    molecularWeight: "~2174.6 g·mol⁻¹ (typical)",
    formula: "See research documentation",
    sequence: "MRWQEMGYIFYPRKLR (typical human MOTS-c sequence)",
    appearance: "Lyophilized solid",
    storage: "Frozen, dry, protected from light.",
    researchNotes: "Research grade only. Not FDA approved.",
    tags: ["MOTS-c", "40mg"],
  },
  {
    id: "nad-1000",
    sku: "NAD-1000",
    name: "NAD+",
    strength: "1000 mg",
    form: "Research chemical (β-nicotinamide adenine dinucleotide)",
    category: "Cofactor / nucleotide research",
    unitPrice: 80,
    unit: "vial",
    image: "images/products/nad-light.jpeg",
    images: [
      "images/products/nad-light.jpeg",
      "images/products/nad-dark.jpeg",
      {
        src: "images/products/coas/nad-1000-coa-p1.png",
        kind: "coa",
        label: "COA",
        alt: "Certificate of Analysis — NAD+ 1000 mg (view only)",
      },
    ],
    shortDescription: "Research-grade NAD+, 1000 mg, laboratory biochemical only.",
    description:
      "Nicotinamide adenine dinucleotide (NAD+, oxidized form) is research-grade laboratory material. Not FDA approved as a drug or supplement. Not for human injection, infusion, or dietary use.",
    scientificName: "β-Nicotinamide adenine dinucleotide (oxidized), NAD+",
    molecularWeight: "663.43 g·mol⁻¹",
    formula: "C₂₁H₂₆N₇O₁₄P₂",
    sequence: "N/A (dinucleotide cofactor)",
    appearance: "White to yellowish solid or lyophilized material (lot-dependent)",
    storage: "Store cold, dry, protected from light and moisture.",
    researchNotes: "Research grade only. Not FDA approved. Handle under institutional chemical hygiene plans.",
    tags: ["NAD+", "1000mg"],
  },
  {
    id: "wolverine",
    sku: "WOLVERINE",
    name: "Wolverine Stack",
    strength: "Stack",
    form: "Multi-vial research stack",
    category: "Stacks",
    unitPrice: 100,
    unit: "stack",
    image: "images/products/wolverine-light.jpeg",
    images: [
      "images/products/wolverine-light.jpeg",
      "images/products/bpc-157-light.jpeg",
      "images/products/tb500-light.jpeg",
    ],
    shortDescription:
      "Research stack: BPC-157 10 mg + TB-500 10 mg.",
    description:
      "Wolverine is a research-grade stack pairing BPC-157 (10 mg) and TB-500 (10 mg) for laboratory programs. Not FDA approved. Not for human or veterinary use. Not a compounded drug product.",
    scientificName: "BPC-157 + TB-500 research stack",
    molecularWeight: "See BPC-157 and TB-500 component specs",
    formula: "Multi-vial stack",
    sequence: "See components",
    appearance: "Research vials as packed",
    storage: "Frozen, dry, protected from light.",
    blendComponents: [
      { name: "BPC-157", amount: "10 mg", mw: "1419.5 g·mol⁻¹ (typical)" },
      { name: "TB-500", amount: "10 mg", mw: "Batch-defined" },
    ],
    researchNotes: "Research grade stack only. Not FDA approved.",
    tags: ["stack", "Wolverine", "BPC-157", "TB-500"],
  },
  {
    id: "nad-ghk",
    sku: "NAD-GHK",
    name: "NAD+ + GHK-Cu Bundle",
    strength: "1000 mg + 100 mg",
    form: "Multi-vial research bundle",
    category: "Bundles",
    unitPrice: 120,
    unit: "bundle",
    image: "images/products/nad-light.jpeg",
    images: [
      "images/products/nad-light.jpeg",
      "images/products/nad-dark.jpeg",
      "images/products/klow-light.jpeg",
      "images/products/klow-dark.jpeg",
    ],
    shortDescription:
      "Research bundle: NAD+ 1000 mg + GHK-Cu 100 mg.",
    description:
      "Paired research-grade materials: NAD+ (1000 mg) and GHK-Cu (100 mg) for laboratory use only. Not FDA approved. Not for human or veterinary use.",
    scientificName: "NAD+ + GHK-Cu research bundle",
    molecularWeight: "NAD+ 663.43 g·mol⁻¹; GHK-Cu complex ~403.9 g·mol⁻¹ (typical)",
    formula: "Multi-vial bundle",
    sequence: "See components",
    appearance: "Research vials as packed",
    storage: "Cold/dry per component storage guidance.",
    blendComponents: [
      { name: "NAD+", amount: "1000 mg", mw: "663.43 g·mol⁻¹" },
      { name: "GHK-Cu", amount: "100 mg", mw: "~403.9 g·mol⁻¹ (complex, typical)" },
    ],
    researchNotes: "Research grade bundle only. Not FDA approved.",
    tags: ["bundle", "NAD+", "GHK-Cu"],
  },
  {
    id: "reta-klow",
    sku: "RETA-KLOW",
    name: "Reta + KLOW Bundle",
    strength: "30 mg + 80 mg",
    form: "Multi-vial research bundle",
    category: "Bundles",
    unitPrice: 200,
    unit: "bundle",
    image: "images/products/reta-klow.jpeg",
    images: [
      "images/products/reta-klow.jpeg",
      "images/products/klow-light.jpeg",
      "images/products/klow-dark.jpeg",
    ],
    shortDescription:
      "Research bundle: Reta (GLP-3 RT) 30 mg + KLOW blend 80 mg.",
    description:
      "Research-grade bundle pairing Reta / GLP-3 RT (30 mg) with KLOW (80 mg total: GHK-Cu 50 mg, TB-500 10 mg, BPC-157 10 mg, KPV 10 mg). Not FDA approved. Not for human or veterinary use.",
    scientificName: "Reta (GLP-3 RT) + KLOW research bundle",
    molecularWeight: "See component specs",
    formula: "Multi-vial bundle",
    sequence: "See components",
    appearance: "Research vials as packed",
    storage: "Frozen, dry, protected from light.",
    blendComponents: [
      { name: "Reta (GLP-3 RT)", amount: "30 mg", mw: "Batch-dependent" },
      { name: "KLOW blend", amount: "80 mg total", mw: "See KLOW components" },
    ],
    researchNotes: "Research grade bundle only. Not FDA approved.",
    tags: ["bundle", "Reta", "KLOW"],
  },
];

/** Catalog products only (excludes listed: false). Full data remains in BW_PRODUCTS. */
window.BW_listedProducts = function () {
  return (window.BW_PRODUCTS || []).filter((p) => p.listed !== false);
};

window.BW_getProduct = function (idOrSku, opts) {
  const q = String(idOrSku || "").toLowerCase();
  const includeUnlisted = opts && opts.includeUnlisted;
  const list = includeUnlisted ? window.BW_PRODUCTS || [] : window.BW_listedProducts();
  return (
    list.find((p) => p.id.toLowerCase() === q || p.sku.toLowerCase() === q) || null
  );
};

/** Fallback image if a product photo fails to load */
window.BW_IMG_FALLBACK = "images/products/klow-light.jpeg";
