/**
 * 220 BioWorX — Research catalog (RUO)
 * Images: light + dark variants where available under images/products/
 * All materials: Research Use Only. Not for human or veterinary use.
 */
window.BW_PRODUCTS = [
  {
    id: "glp3-rt-30",
    sku: "RETA-30",
    name: "Reta (GLP-3 RT)",
    strength: "30 mg",
    form: "Lyophilized research peptide",
    category: "Incretin-pathway research",
    unitPrice: 140,
    unit: "vial",
    image: "images/products/glp3-rt-30.svg",
    images: ["images/products/glp3-rt-30.svg"],
    shortDescription:
      "Research-grade Reta / GLP-3 RT, 30 mg, for controlled laboratory investigation of multi-agonist incretin pathway models.",
    description:
      "Reta (GLP-3 RT) 30 mg is provided strictly for Research Use Only as a lyophilized research peptide. Intended for qualified laboratories studying multi-receptor incretin-related signaling in non-clinical research systems. Not a drug, not a compounded medication, and not for human or veterinary use.",
    scientificName: "Reta / GLP-3 RT (research designation)",
    cas: "Research material — see COA / lot documentation when supplied",
    molecularWeight: "See lot COA (multi-agonist research peptide; confirm per batch)",
    formula: "See sequence / COA documentation",
    sequence: "Lot-specific documentation on request for qualified research accounts",
    purity: "Research grade; purity stated on lot COA when provided",
    appearance: "White to off-white lyophilized solid (typical)",
    storage: "Store lyophilized material frozen, protected from light and moisture. Handling per laboratory SOP only.",
    researchNotes: "Photo pack pending for this SKU — placeholder shown until dedicated Reta vial images are uploaded.",
    tags: ["reta", "GLP-3", "30mg"],
  },
  {
    id: "tirz-40",
    sku: "TIRZ-40",
    name: "Tirz (GLP)",
    strength: "40 mg",
    form: "Lyophilized research peptide",
    category: "Incretin-pathway research",
    unitPrice: 150,
    unit: "vial",
    image: "images/products/tirz-light.jpeg",
    images: [
      "images/products/tirz-light.jpeg",
      "images/products/tirz-dark.jpeg",
    ],
    shortDescription:
      "Tirz-class dual incretin pathway research peptide, 40 mg per vial.",
    description:
      "Tirz 40 mg is supplied for Research Use Only for laboratory research exploring dual incretin-related receptor pathways in non-clinical settings. Not for human consumption, clinical administration, or compounding into patient medications.",
    scientificName: "Tirz-class dual incretin pathway research peptide",
    cas: "See COA / supplier documentation for lot identity",
    molecularWeight: "~4810–4814 g·mol⁻¹ (typical literature range; confirm on lot COA)",
    formula: "See sequence documentation / COA",
    sequence: "Available to qualified research purchasers with lot documentation",
    purity: "Research grade; see lot COA",
    appearance: "Lyophilized solid",
    storage: "Frozen, dry, protected from light. Handle under laboratory controls only.",
    researchNotes: "Not FDA approved for any use. Research Use Only.",
    tags: ["tirz", "incretin", "40mg"],
  },
  {
    id: "bpc-157-10",
    sku: "BPC-157-10",
    name: "BPC-157",
    strength: "10 mg",
    form: "Lyophilized research peptide",
    category: "Synthetic peptide research",
    unitPrice: 40,
    unit: "vial",
    image: "images/products/bpc-157-light.jpeg",
    images: [
      "images/products/bpc-157-light.jpeg",
      "images/products/bpc-157-dark.jpeg",
    ],
    shortDescription:
      "Synthetic pentadecapeptide research material (BPC-157), 10 mg.",
    description:
      "BPC-157 is offered solely as a Research Use Only chemical for in vitro and other lawful laboratory research. Not intended for human or animal clinical use. No therapeutic claims are made.",
    scientificName: "BPC-157 (GEPPPGKPADDAGLV; research pentadecapeptide)",
    cas: "137525-51-0 (commonly cited; verify lot identity)",
    molecularWeight: "1419.5 g·mol⁻¹ (typical)",
    formula: "C₆₂H₉₈N₁₆O₂₂ (typical)",
    sequence: "Gly-Glu-Pro-Pro-Pro-Gly-Lys-Pro-Ala-Asp-Asp-Ala-Gly-Leu-Val (GEPPPGKPADDAGLV)",
    purity: "Research grade; see lot COA",
    appearance: "White to off-white lyophilized powder (typical)",
    storage: "−20 °C recommended for long-term storage of lyophilizate; protect from moisture and light.",
    researchNotes: "Research Use Only. Confirm SKU on order.",
    tags: ["BPC-157", "10mg"],
  },
  {
    id: "tb-500-10",
    sku: "TB-500-10",
    name: "TB-500",
    strength: "10 mg",
    form: "Lyophilized research peptide",
    category: "Synthetic peptide research",
    unitPrice: 60,
    unit: "vial",
    image: "images/products/tb500-light.jpeg",
    images: [
      "images/products/tb500-light.jpeg",
      "images/products/tb500-dark.jpeg",
    ],
    shortDescription:
      "TB-500 research peptide, 10 mg per vial, for non-clinical laboratory research.",
    description:
      "TB-500 is supplied for Research Use Only. Confirm exact identity and sequence on the lot Certificate of Analysis. Not for human or veterinary use.",
    scientificName: "TB-500 (thymosin β4–related research peptide; lot-defined)",
    cas: "Lot-defined — confirm on COA",
    molecularWeight: "Lot-defined (confirm on COA)",
    formula: "See lot COA",
    sequence: "See lot COA / specification sheet",
    purity: "Research grade; see lot COA",
    appearance: "Lyophilized solid",
    storage: "Store frozen, dry, protected from light.",
    researchNotes: "Always match vial label, COA, and order SKU.",
    tags: ["TB-500", "10mg"],
  },
  {
    id: "klow-80",
    sku: "KLOW-80",
    name: "KLOW Blend",
    strength: "80 mg total",
    form: "Lyophilized multi-peptide research blend",
    category: "Research blends",
    unitPrice: 80,
    unit: "vial",
    image: "images/products/klow-light.jpeg",
    images: [
      "images/products/klow-light.jpeg",
      "images/products/klow-dark.jpeg",
    ],
    shortDescription:
      "80 mg research blend: 50 mg GHK-Cu, 10 mg TB-500, 10 mg BPC-157, 10 mg KPV.",
    description:
      "KLOW is a multi-component lyophilized research blend totaling 80 mg per vial. Composition (label claim): GHK-Cu 50 mg, TB-500 10 mg, BPC-157 10 mg, KPV 10 mg. Research Use Only. Not for human or veterinary use. Not a 503A/503B compounded drug.",
    scientificName: "KLOW multi-peptide research blend",
    cas: "Mixture — see component CAS on COA where applicable",
    molecularWeight: "Component-specific (see blend breakdown)",
    formula: "Multi-component blend",
    sequence: "See individual components",
    purity: "Research grade blend; component purity per COA",
    appearance: "Lyophilized solid (color may reflect copper-peptide component)",
    storage: "Frozen, dry, protected from light.",
    blendComponents: [
      { name: "GHK-Cu", amount: "50 mg", mw: "~403.9 g·mol⁻¹ (complex; peptide ~340.4)" },
      { name: "TB-500", amount: "10 mg", mw: "Lot-defined" },
      { name: "BPC-157", amount: "10 mg", mw: "1419.5 g·mol⁻¹ (typical)" },
      { name: "KPV", amount: "10 mg", mw: "342.4 g·mol⁻¹ (typical)" },
    ],
    researchNotes: "Independent analytical verification recommended for critical protocols.",
    tags: ["blend", "KLOW", "80mg"],
  },
  {
    id: "kpv-10",
    sku: "KPV-10",
    name: "KPV",
    strength: "10 mg",
    form: "Lyophilized research peptide",
    category: "Synthetic peptide research",
    unitPrice: 50,
    unit: "vial",
    image: "images/products/kpv-10.svg",
    images: ["images/products/kpv-10.svg"],
    shortDescription: "KPV tripeptide research material, 10 mg.",
    description:
      "KPV (Lys-Pro-Val) is a synthetic tripeptide supplied for Research Use Only. Not for human or veterinary administration or consumption.",
    scientificName: "KPV (L-lysyl-L-prolyl-L-valine)",
    cas: "67727-97-3 (commonly cited; verify lot)",
    molecularWeight: "342.4 g·mol⁻¹ (typical)",
    formula: "C₁₆H₃₀N₄O₄ (typical)",
    sequence: "Lys-Pro-Val (KPV)",
    purity: "Research grade; see lot COA",
    appearance: "Lyophilized solid",
    storage: "Frozen, dry, protected from light.",
    researchNotes: "Dedicated light/dark product photos pending — placeholder until uploaded.",
    tags: ["KPV", "10mg"],
  },
  {
    id: "ghk-cu-100",
    sku: "GHK-CU-100",
    name: "GHK-Cu",
    strength: "100 mg",
    form: "Lyophilized research copper peptide",
    category: "Copper peptide research",
    unitPrice: 50,
    unit: "vial",
    image: "images/products/klow-light.jpeg",
    images: [
      "images/products/klow-light.jpeg",
      "images/products/klow-dark.jpeg",
    ],
    shortDescription:
      "GHK-Cu copper tripeptide research material, 100 mg, for laboratory use only.",
    description:
      "Glycyl-L-histidyl-L-lysine copper complex (GHK-Cu) is supplied for Research Use Only as a laboratory research material. Not for human or veterinary use, cosmetic consumer use claims, or clinical administration.",
    scientificName: "GHK-Cu (glycyl-L-histidyl-L-lysine copper complex)",
    cas: "89030-95-5 (commonly cited for GHK-Cu; verify lot)",
    molecularWeight: "Peptide ~340.4 g·mol⁻¹; Cu complex ~403.9 g·mol⁻¹ (typical)",
    formula: "C₁₄H₂₄N₆O₄ · Cu (typical complex representation)",
    sequence: "Gly-His-Lys (GHK) complexed with copper(II)",
    purity: "Research grade; see lot COA",
    appearance: "Blue to blue-green lyophilized solid (typical for Cu peptide)",
    storage: "Frozen, dry, protected from light.",
    researchNotes:
      "Standalone GHK-Cu 100 mg SKU. Temporary gallery uses KLOW pack imagery until dedicated GHK-Cu photos are added.",
    tags: ["GHK-Cu", "100mg"],
  },
  {
    id: "cjc-ipa-20",
    sku: "CJC-IPA-20",
    name: "CJC-1295 (No DAC) + Ipamorelin",
    strength: "10 mg + 10 mg (20 mg total)",
    form: "Lyophilized dual-peptide research vial",
    category: "GHRH / GHS pathway research",
    unitPrice: 100,
    unit: "vial",
    image: "images/products/cjc-ipa-light.jpeg",
    images: [
      "images/products/cjc-ipa-light.jpeg",
      "images/products/cjc-ipa-dark.jpeg",
    ],
    shortDescription:
      "Dual research vial: CJC-1295 without DAC 10 mg + Ipamorelin 10 mg (20 mg total).",
    description:
      "Dual-fill research vial providing CJC-1295 (No DAC) 10 mg and Ipamorelin 10 mg for laboratory research into GHRH-analogue and ghrelin-mimetic pathway models. Research Use Only.",
    scientificName: "CJC-1295 (modGRF 1-29, no DAC) + Ipamorelin",
    cas: "Component-specific — see COA",
    molecularWeight:
      "CJC-1295 no DAC ~3367.9 g·mol⁻¹ (typical); Ipamorelin ~711.9 g·mol⁻¹ (typical)",
    formula: "See component documentation",
    sequence:
      "CJC-1295 (No DAC): modified GRF(1-29) analogue without Drug Affinity Complex. Ipamorelin: Aib-His-D-2-Nal-D-Phe-Lys-NH₂ (typical).",
    purity: "Research grade; see lot COA",
    appearance: "Lyophilized solid",
    storage: "Frozen, dry, protected from light.",
    blendComponents: [
      { name: "CJC-1295 (No DAC)", amount: "10 mg", mw: "~3367.9 g·mol⁻¹ (typical)" },
      { name: "Ipamorelin", amount: "10 mg", mw: "~711.9 g·mol⁻¹ (typical)" },
    ],
    researchNotes: "Confirm structure on COA. Research Use Only.",
    tags: ["CJC-1295", "Ipamorelin", "20mg"],
  },
  {
    id: "mots-c-40",
    sku: "MOTSC-40",
    name: "MOTS-c",
    strength: "40 mg",
    form: "Lyophilized research peptide",
    category: "Mitochondrial peptide research",
    unitPrice: 75,
    unit: "vial",
    image: "images/products/motsc-light.jpeg",
    images: [
      "images/products/motsc-light.jpeg",
      "images/products/motsc-dark.jpeg",
    ],
    shortDescription:
      "MOTS-c mitochondrial-derived peptide research material, 40 mg.",
    description:
      "MOTS-c is a mitochondrial open reading frame–encoded peptide supplied for Research Use Only. For laboratory investigation of mitochondrial signaling models. Not for human or veterinary use.",
    scientificName: "MOTS-c (mitochondrial ORF-derived peptide)",
    cas: "1627580-64-6 (commonly cited; verify lot)",
    molecularWeight: "~2174.6 g·mol⁻¹ (typical)",
    formula: "See literature / COA",
    sequence: "MRWQEMGYIFYPRKLR (typical — confirm lot)",
    purity: "Research grade; see lot COA",
    appearance: "Lyophilized solid",
    storage: "Frozen, dry, protected from light.",
    researchNotes: "Verify sequence/MW against lot COA.",
    tags: ["MOTS-c", "40mg"],
  },
  {
    id: "nad-1000",
    sku: "NAD-1000",
    name: "NAD+",
    strength: "1000 mg",
    form: "Research chemical (β-nicotinamide adenine dinucleotide)",
    category: "Cofactor / nucleotide research",
    unitPrice: 80,
    unit: "vial",
    image: "images/products/nad-light.jpeg",
    images: [
      "images/products/nad-light.jpeg",
      "images/products/nad-dark.jpeg",
    ],
    shortDescription: "NAD+ research material, 1000 mg, laboratory biochemical RUO.",
    description:
      "Nicotinamide adenine dinucleotide (NAD+, oxidized form) is supplied for Research Use Only as a laboratory biochemical. Not for human injection, infusion, or dietary use.",
    scientificName: "β-Nicotinamide adenine dinucleotide (oxidized), NAD+",
    cas: "53-84-9",
    molecularWeight: "663.43 g·mol⁻¹",
    formula: "C₂₁H₂₆N₇O₁₄P₂",
    sequence: "N/A (dinucleotide cofactor)",
    purity: "Research grade; see lot COA",
    appearance: "White to yellowish solid or lyophilized material (lot-dependent)",
    storage: "Store cold, dry, protected from light and moisture per COA.",
    researchNotes: "Handle under institutional chemical hygiene plans.",
    tags: ["NAD+", "1000mg"],
  },

  /* ——— Bundles ——— */
  {
    id: "wolverine",
    sku: "WOLVERINE",
    name: "Wolverine Bundle",
    strength: "Bundle",
    form: "Multi-vial research bundle",
    category: "Bundles",
    unitPrice: 100,
    unit: "bundle",
    image: "images/products/wolverine-light.jpeg",
    images: ["images/products/wolverine-light.jpeg"],
    shortDescription:
      "Wolverine research bundle: BPC-157 10 mg + TB-500 10 mg (paired research vials).",
    description:
      "Wolverine is a research bundle pairing BPC-157 (10 mg) and TB-500 (10 mg) for laboratory programs that require both materials. Research Use Only. Not for human or veterinary use. Not a compounded drug product.",
    scientificName: "BPC-157 + TB-500 research bundle",
    cas: "See component listings",
    molecularWeight: "See BPC-157 and TB-500 component specs",
    formula: "Multi-vial bundle",
    sequence: "See components",
    purity: "Research grade; see lot COAs for each vial",
    appearance: "Two lyophilized research vials (as packed)",
    storage: "Frozen, dry, protected from light.",
    blendComponents: [
      { name: "BPC-157", amount: "10 mg", mw: "1419.5 g·mol⁻¹ (typical)" },
      { name: "TB-500", amount: "10 mg", mw: "Lot-defined" },
    ],
    researchNotes:
      "Bundle composition: BPC-157 10 mg + TB-500 10 mg unless otherwise stated on packing list.",
    tags: ["bundle", "Wolverine", "BPC-157", "TB-500"],
  },
  {
    id: "nad-ghk",
    sku: "NAD-GHK",
    name: "NAD+ + GHK-Cu Bundle",
    strength: "1000 mg + 100 mg",
    form: "Multi-vial research bundle",
    category: "Bundles",
    unitPrice: 130,
    unit: "bundle",
    image: "images/products/nad-light.jpeg",
    images: [
      "images/products/nad-light.jpeg",
      "images/products/nad-dark.jpeg",
      "images/products/klow-light.jpeg",
    ],
    shortDescription:
      "Research bundle: NAD+ 1000 mg + GHK-Cu 100 mg.",
    description:
      "Paired research materials: NAD+ (1000 mg) and GHK-Cu (100 mg) for laboratory use only. Research Use Only. Not for human or veterinary use.",
    scientificName: "NAD+ + GHK-Cu research bundle",
    cas: "See component listings",
    molecularWeight: "NAD+ 663.43 g·mol⁻¹; GHK-Cu complex ~403.9 g·mol⁻¹ (typical)",
    formula: "Multi-vial bundle",
    sequence: "See components",
    purity: "Research grade; see lot COAs",
    appearance: "Two research vials as packed",
    storage: "Cold/dry per component COA recommendations.",
    blendComponents: [
      { name: "NAD+", amount: "1000 mg", mw: "663.43 g·mol⁻¹" },
      { name: "GHK-Cu", amount: "100 mg", mw: "~403.9 g·mol⁻¹ (complex, typical)" },
    ],
    researchNotes: "Dedicated bundle pack photo pending; gallery uses component imagery.",
    tags: ["bundle", "NAD+", "GHK-Cu"],
  },
  {
    id: "reta-klow",
    sku: "RETA-KLOW",
    name: "Reta + KLOW Bundle",
    strength: "30 mg + 80 mg",
    form: "Multi-vial research bundle",
    category: "Bundles",
    unitPrice: 200,
    unit: "bundle",
    image: "images/products/reta-klow.jpeg",
    images: ["images/products/reta-klow.jpeg"],
    shortDescription:
      "Research bundle: Reta (GLP-3 RT) 30 mg + KLOW blend 80 mg.",
    description:
      "Reta + KLOW pairs Reta / GLP-3 RT (30 mg) with the KLOW multi-peptide blend (80 mg total: GHK-Cu 50 mg, TB-500 10 mg, BPC-157 10 mg, KPV 10 mg). Research Use Only. Not for human or veterinary use.",
    scientificName: "Reta (GLP-3 RT) + KLOW research bundle",
    cas: "See component listings",
    molecularWeight: "See component specs",
    formula: "Multi-vial bundle",
    sequence: "See components",
    purity: "Research grade; see lot COAs",
    appearance: "Research vials as packed",
    storage: "Frozen, dry, protected from light.",
    blendComponents: [
      { name: "Reta (GLP-3 RT)", amount: "30 mg", mw: "See lot COA" },
      { name: "KLOW blend", amount: "80 mg total", mw: "See KLOW components" },
    ],
    researchNotes: "Include cart reference on payment. Research Use Only.",
    tags: ["bundle", "Reta", "KLOW"],
  },
];

window.BW_getProduct = function (idOrSku) {
  const q = String(idOrSku || "").toLowerCase();
  return (
    window.BW_PRODUCTS.find(
      (p) => p.id.toLowerCase() === q || p.sku.toLowerCase() === q
    ) || null
  );
};
